import Head from "next/head";
import {
  // AiFillTwitterCircle,
  // AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/i.webp";
import design from "../public/p.webp";
import consulting from "../public/x.webp";
import Image from "next/image";

import illustrator1 from "../public/illustrator1.jpeg"
import illustrator2 from "../public/illustrator2.jpeg"
import illustrator3 from "../public/illustrator3.jpeg"
import illustrator4 from "../public/illustrator4.jpeg"
import web1 from "../public/web1.jpg"
import web2 from "../public/web2.jpg"
import web3 from "../public/web3.jpg"
import web4 from "../public/web4.jpg"
import web5 from "../public/web5.jpg"
import web6 from "../public/web6.jpg"
import mob1 from "../public/mobiled1.jpg"
import mob2 from "../public/mobiled2.jpg"
import mob3 from "../public/mobiled3.jpg"
import mob4 from "../public/mobiled4.jpg"
import mob5 from "../public/mobiled5.jpg"



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [user, setUser] = useState({
    name: "",
    email: "",
    description: "",
  });

  let name, value;

  const handleInput = (e) => {
    console.log(e);
    name = e.target.name;

    value = e.target.value;

    setUser({ ...user, [name]: value });
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Basit Ali</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Basit Ali</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href=""
                >
                  Fiverr Profile
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Hello, I,m <br /> Basit Ali
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Graphic designer.
            </h3>
            <p className="mt-5 text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer providing services of graphic designs and other design
              content needs.
            </p>
            {/* <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://twitter.com/SuhaibA53198140">
                <AiFillTwitterCircle />
              </a>
              <a href="https://www.linkedin.com/in/suhaibinsari/">
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/suhaibinsari">
                <AiFillGithub />
              </a>
            </div> */}
            <div className=" mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-10 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a designer. I've
              done local work for many
              <span className="text-teal-500"> clients </span>
              I can help you creating unique designs. lets get connected.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            <span className="text-teal-500">  My Services </span> <br/>
              Logo design,
              Cartoon & comics,
              Packaging & label design, 
              Social media design, 
              Book design, 
              Flyer design,
              Poster design,
              Pattern Design,
              Illustration,
              App design, 
              Website design.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">Photoshop </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs in Photoshop
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Illustrator </h3>
              <p className="py-2">
              Creating elegant designs suited for your needs in illustrator
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Xd</h3>
              <p className="py-2">
              Creating elegant designs suited for your mobile or web in adobe xd
              </p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">My Portofolio</h3>
          </div>
          <span className="text-2xl py-2 text-teal-600 font-medium">
            illustrator
          </span>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={illustrator1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={illustrator2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={illustrator3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={illustrator4}
              />
            </div>
{/* <></> */}
            </div>
          <span className="text-2xl py-2 text-teal-600 font-medium">
            Web Design
          </span>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/2 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/2 flex-1">
              <Image
                className="rounded-lg object-cover"
                layout="responsive"
                src={web2}
              />
            </div>
            
            <div className="basis-1/2 flex-1">
              <Image
                className="rounded-lg object-cover"
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/2 flex-1">
              <Image
                className="rounded-lg object-cover"
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/2 flex-1">
              <Image
                className="rounded-lg object-cover"
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/2 flex-1">
              <Image
                className="rounded-lg object-cover"
                layout="responsive"
                src={web6}
              />
            </div>
           
              
           
          </div>
          {/*  */}

          <span className="text-2xl py-2 text-teal-600 font-medium">
            Mobile Design
          </span>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/2 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                layout="responsive"
                src={mob1}
              />
            </div>
            <div className="basis-1/2 flex-1">
              <Image
                className="rounded-lg object-cover"
                layout="responsive"
                src={mob2}
              />
            </div>
            
            <div className="basis-1/2 flex-1">
              <Image
                className="rounded-lg object-cover"
                layout="responsive"
                src={mob3}
              />
            </div>
            <div className="basis-1/2 flex-1">
              <Image
                className="rounded-lg object-cover"
                layout="responsive"
                src={mob4}
              />
            </div>
            <div className="basis-1/2 flex-1">
              <Image
                className="rounded-lg object-cover"
                layout="responsive"
                src={mob5}
              />
            </div>
          </div>

        </section>
        <section>
          <div class="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800  flex-1">
            <form>
              <label class="block mb-6 ">
                <p class="text-left text-gray-700 dark:text-white ">
                  Your name
                </p>
                <input
                  type="text"
                  name="name"
                  class="
              block
              w-full
              mt-1
              border-gray-300
              rounded-md
              shadow-sm
              focus:border-indigo-300
              focus:ring
              focus:ring-indigo-200
              focus:ring-opacity-50 p-2
            "
                  placeholder="someOne"
                  value={user.name}
                  onChange={handleInput}
                />
              </label>
              <label class="block mb-6">
                <p class="text-left text-gray-700 dark:text-white">
                  Email address
                </p>
                <input
                  name="email"
                  type="email"
                  class="
              block
              w-full
              mt-1
              border-gray-300
              rounded-md
              shadow-sm
              focus:border-indigo-300
              focus:ring
              focus:ring-indigo-200
              focus:ring-opacity-50 p-2
            "
                  placeholder="someone@example.com"
                  value={user.email}
                  onChange={handleInput}
                  required
                />
              </label>
              <label class="block mb-6">
                <p class="text-left text-gray-700 dark:text-white">Message</p>
                <textarea
                  name="description"
                  type="text"
                  class="
              block
              w-full
              mt-1
              border-gray-300
              rounded-md
              shadow-sm
              focus:border-indigo-300
              focus:ring
              focus:ring-indigo-200
              focus:ring-opacity-50 p-2
            "
                  rows="3"
                  placeholder="Tell me what you're thinking about..."
                  value={user.description}
                  onChange={handleInput}
                ></textarea>
              </label>
              <div class="mb-6">
                <button
                  type="text"
                  class="
              h-10
              px-5
              text-indigo-100
              bg-indigo-700
              rounded-lg
              transition-colors
              duration-150
              focus:shadow-outline
              hover:bg-indigo-800 
            "
                >
                  Submit
                </button>
              </div>
            </form>
          </div>
        </section>
        <section>
          <footer class="p-4 bg-white rounded-lg shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800">
            <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">
              © 2022 Made with ❤️
            </span>
            <ul class="flex flex-wrap items-center mt-3 text-sm text-gray-500 dark:text-gray-400 sm:mt-0">
              <li>
                <a href="https://github.com/suhaibinsari" class="hover:underline"><AiFillGithub /></a>
              </li>
            </ul>
          </footer>
        </section>
      </main>
    </div>
  );
}
